WELCOME_MESSAGE_ID = 1
INPUT_MESSAGE_ID = 2
WORLD_MESSAGE_ID = 3

LASER_WEAPON_ID = 1
DOUBLE_FIRE_WEAPON_ID = 2
SPREAD_FIRE_WEAPON_ID = 3
RAPID_FIRE_WEAPON_ID = 4
ROCKET_WEAPON_ID = 5
ROCKET_SALVO_WEAPON_ID = 6
TIME_BOMB_WEAPON_ID = 7
PROXIMITY_MINE_WEAPON_ID = 8
